name: TypeScript Canary
on:
  schedule:
    # Every Thursday at 21.15
    - cron: '15 21 * * 4'
  workflow_dispatch:
jobs:
  types:
    name: TypeScript ${{ matrix.typescript-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        typescript-version:
          - next
          - latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - run: npm install
      - run: npm install typescript@${{ matrix.typescript-version }}
      - name: show installed typescript version
        run: npm list typescript --depth=0
      - run: NODE_OPTIONS="--max-old-space-size=6144" npx tsc
